name: dl_assignment

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scikit-learn=1.0.2
  - pandas-profiling=3.1.0
  - pandas=1.3.5
  - pip=20.3.3
  - pip: 
    - tfx==1.5.0
    - pyparsing==2.4.2
